# Generated by Django 5.2.6 on 2025-10-02 06:32

import django.db.models.deletion
import wger.exercises.models.image
import wger.utils.images
from django.db import migrations, models


def update_image_dimensions(apps, schema_editor):
    ExerciseImage = apps.get_model('exercises', 'ExerciseImage')
    for image in ExerciseImage.objects.all():
        if not image.image:
            print(f'ExerciseImage {image.pk} has no corresponding file!')
            continue

        try:
            image.width = image.image.width
            image.height = image.image.height
            image.save(update_fields=['width', 'height'])
        except FileNotFoundError as e:
            print('Error while accessing image file!', e)
            pass


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0033_uniqueness_constraint_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseimage',
            name='height',
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name='Height'
            ),
        ),
        migrations.AddField(
            model_name='exerciseimage',
            name='width',
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name='Width'
            ),
        ),
        migrations.AddField(
            model_name='historicalexerciseimage',
            name='height',
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name='Height'
            ),
        ),
        migrations.AddField(
            model_name='historicalexerciseimage',
            name='width',
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name='Width'
            ),
        ),
        migrations.RunPython(update_image_dimensions, migrations.RunPython.noop),
    ]
